#!/usr/bin/env python

#read in data from grouplens 100k as a 2d dictionary
#create a dictionary of movies
movies={}
for x in open('Desktop/ml-100k/u.item'):
    (id,title,rlsdate)=x.split('|')[0:3]
    movies[id]=title
#create a dictionary of ratings with userid as the first key and movie name as the second key
rate={}
for x in open('Desktop/ml-100k/u.data'):
    (userid,itemid,rating,time)=x.split('\t')
    rate.setdefault(userid,{})
    rate[userid][movies[itemid]]=float(rating)
####################################################


#######################################################################
#PLOT WITH TWO USERS AS AXIS AND THEIR RATINGS FOR A MOVIE AS A POINT
%matplotlib nbagg
import matplotlib.pyplot as plt
import numpy as np

x=[]
y=[]
#movie1 and movie2 are movie names
for movie1 in rate['344']:
    for movie2 in rate['345']:
        if(movie1==movie2):
            x.append(rate['344'][movie1])
            y.append(rate['345'][movie2])         
plt.plot(x,y,'ro')
plt.axis([0,6,0,6])
plt.show()
