#!/usr/bin/env python

#read in data from grouplens 100k as a 2d dictionary
#create a dictionary of movies
movies={}
for x in open('Desktop/ml-100k/u.item'):
    (id,title,rlsdate)=x.split('|')[0:3]
    movies[id]=title
#create a dictionary of ratings with userid as the first key and movie name as the second key
rate={}
for x in open('Desktop/ml-100k/u.data'):
    (userid,itemid,rating,time)=x.split('\t')
    rate.setdefault(userid,{})
    rate[userid][movies[itemid]]=float(rating)
####################################################
mvrate={}
for x in open('Desktop/ml-100k/u.data'):
    (userid,itemid,rating,time)=x.split('\t')
    mvrate.setdefault(userid,{})
    #some movies are not rated by anyone
    mvrate.setdefault(movies[itemid],{})
    mvrate[movies[itemid]][userid]=float(rating)


